# {binary, categorical, float}.py are extracted from here

CAT_FEATURES = {'accessible': ['NORMAL', 'UNDEFINED', 'DEPRECATED', 'INACCESSIBLE'],

                'expectedType': ['normal', 'expected', 'UNDEFINED', 'ofDefaultType', 'maybeExpected',
                                 'unexpected'],

                'kind': ['UNDEFINED',
                         'annoMethod',
                         'classLiteral',
                         'classNameOrGlobalStatic',
                         'collectionFactory',
                         'expectedTypeArgument',
                         'expectedTypeConstant',
                         'expectedTypeMethod',
                         'improbableKeyword',
                         'localOrParameter',
                         'nonInitialized',
                         'normal',
                         'probableKeyword',
                         'qualifiedWithField',
                         'qualifiedWithGetter',
                         'suitableClass',
                         'superMethodParameters'],
                'liftShorter': ['False', 'True', 'UNDEFINED', 'false', 'true'],
                'methodsChains': ['00_0_2147483647', 'UNDEFINED'],
                'middleMatching': ['False', 'True', 'true', 'false', 'UNDEFINED'],
                'recursion': ['delegation', 'recursive', 'UNDEFINED', 'normal'],
                'templates': ['False', 'True', 'true', 'false', 'UNDEFINED'],
                'prox_groovyReferenceListWeigher': ['unknown', 'UNDEFINED'],
                'prox_javaInheritance': ['true', 'null', 'false', 'UNDEFINED'],
                'prox_referenceList': ['unknown', 'inapplicable', 'applicableByKind', 'UNDEFINED']
            }

FLOAT_FEATURES = {'explicitProximity': 0,
                  'query_length': 0,
                  'cerp_length': 0,
                  'sorter': 1,
                  'grouping': 0,
                  'nameEnd': 0,
                  'prefix': 0,
                  'priority': 0,
                  'sameWords': 0,
                  'shorter': 0,
                  'simple': 0,
                  'statics': -3,
                  'stats': 0,
                  'prox_explicitlyImported': 0.0,
                  'prox_knownElement': 0,
                  'prox_sameModule': 0,
                  'prox_samePsiMember': 0,
                  'position': 0}

BIN_FEATURES = {'frozen': {'True': 1, 'False': 0, 'default': 0},
                'liftShorterClasses': {'true': 1, 'false': 0, 'default': 0},
                'nonGeneric': {'0': 0, '1': 1, 'default': 0},
                'prox_inResolveScope': {'true': 1, 'false': 0, 'default': 1},
                'prox_openedInEditor': {'true': 1, 'false': 0, 'default': 0},
                'prox_sameDirectory': {'true': 1, 'false': 0, 'default': 0},
                'prox_sameLogicalRoot': {'true': 1, 'false': 0, 'default': 0},
                'prox_sdkOrLibrary': {'true': 1, 'false': 0, 'default': 0},
                }
